name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  palette-generator:
    name: Palette generator
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: danth
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build palette generator
        run: nix build .#palette-generator
