name: Docs

on:
  push:
    branches:
      - master

jobs:
  pages:
    name: Pages
    uses: danth/coricamu/.github/workflows/pages.yml@cd253a6940853ffc3da7c14c9311940f1d70e222
    with:
      output_name: docs
